spring:
    datasource:
        #DruidDataSource 所需参数
        type: com.alibaba.druid.pool.DruidDataSource 
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/DB_TK?useUnicode=true&characterEncoding=UTF-8
        username: root 
        password: root
        initialSize: 10 
        minIdle: 10 
        maxActive: 30 
        maxWait: 15000 
        timeBetweenEvictionRunsMillis: 120000 
        minEvictableIdleTimeMillis: 300000 
        validationQuery: SELECT 'x' 
        testWhileIdle: true 
        testOnBorrow: false 
        testOnReturn: false 
        poolPreparedStatements: true 
        maxPoolPreparedStatementPerConnectionSize: 20 
        removeAbandoned: true 
        removeAbandonedTimeoutMillis: 20000 
        logAbandoned: true 
        logDifferentThread: true 
        filters: log4j,stat 
        connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000 
        useGlobalDataSourceStat: true 
        # Druid 监控 Servlet 配置参数 
        druidRegistrationUrl: /druid/* 
        resetEnable: true 
        loginUsername: root 
        loginPassword: root 
        # Druid 监控过滤相关配置参数 
        filtersUrlPatterns: /* 
        exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
        sessionStatMaxCount: 2000 
        sessionStatEnable: true 
        principalSessionName: session_user_key 
        profileEnable: true
logging:
  config: classpath:logback-prod.xml